const bgcolors = [
  { name: 'Jon Snow', value: '#FFFFFF', default: true },
  { name: 'darkness', value: '#000000' },
  { name: 'bubble', value: '#5AB9EA' },
  { name: 'element', value: '#5680E9' },
  { name: 'empire', value: '#3500D3' },
  { name: 'market', value: '#25274D' },
  { name: 'wild', value: '#2F2FA2' },
  { name: 'cotton', value: '#8860D0' },
  { name: 'heavy', value: '#A64AC9' },
  { name: 'liberty', value: '#3FEEE6' },
  { name: 'royalty', value: '#5CDB95' },
  { name: 'studio', value: '#14A76C' },
  { name: 'progress', value: '#254E58' },
  { name: 'umbrella', value: '#F8E9A1' },
  { name: 'party', value: '#FFE400' },
  { name: 'network', value: '#FF652F' },
  { name: 'arena', value: '#F4976C' },
  { name: 'hell', value: '#FC4445' },
  { name: 'valley', value: '#D83F87' },
  { name: 'missile', value: '#DA7B93' },
  { name: 'gainsboro', value: '#DCDCDC' },
  { name: 'lightgrey', value: '#D3D3D3' },
  { name: 'silver', value: '#C0C0C0' },
  { name: 'grey', value: '#A9A9A9' },
  { name: 'darkgrey', value: '#808080' },
  { name: 'dimgrey', value: '#696969' },
];

export default bgcolors;
